---
title: "Politisk holdningsdannelse II:<br>Motivated reasoning and heuristics"
subtitle: "Dansk og Komparativ Politik 2 forelæsning #5"
author: "Søren Damsbo-Svendsen"
institute: Institut for statskundskab<br>Københavns Universitet
date: "`r format(Sys.Date(), '%d-%m-%Y')`"
output:
  xaringan::moon_reader:
    css: ["default", "https://soerendamsbo.github.io/misc-slides/template.css"]
    self_contained: true
    nature: 
      ratio: '16:9'
      highlightLines: true
      countincrementalSlides: false
---

```{r, include = FALSE}

pacman::p_load(tidyverse, 
               knitr, 
               lubridate, 
               kableExtra,
               xaringan,
               xaringanExtra)

knitr::opts_chunk$set(echo = FALSE, 
                      fig.align = "center", 
                      cache = TRUE,
                      out.width="1000px"
                      )

Sys.setlocale(locale = "da_DK.UTF-8")

xaringanExtra::use_tile_view()

```

<!--- NOTER

- Masser af klimaeksempler (evt. klimagrafer)

Unlike the RAS model, motivated reasoning explicitly allows attitudes to
change in the direction opposite the message, i.e., a conservative message can make a liberal’s
attitude even more liberal. In the RAS model, this outcome occurs only stochastically through the
“sampling” process ... Attitude polarization in response to partisan media exposure is thus a typical outcome
in Zaller’s RAS model and theories of motivated reasoning (Prior, 2013).

In the motivated reasoning framework, Taber & Lodge (2006, p. 756) caution that attitude polarization may not occur when a message fails to
“arouse sufficient partisan motivation to induce much biased processing.” Instead of polarizing audience attitudes, slanted news may thus move everyone in the same direction, especially when audience members lack political knowledge or strong prior attitudes. As Chong & Druckman
(e.g., 2007) demonstrate, the strength of arguments also affects the likelihood of persuasion. ... In both the RAS model and the motivated reasoning framework, exposure even to balanced or neutral news can lead to attitude polarization

SLIDES START --->

---

# Puzzle

Meme med Jack Nicholson: Psykologiske tilbøjeligheder

Hvordan det kan producere mønstre i public opinion, ikke mindst polarisering.

Quick attention capturing opening (controversy or puzzle)

Hvad er det, vi gerne vil forstå eller kunne forklare?

Bedre forståelse for din skøre onkel

---

# State the key point or thesis

Politisk psykologi: Mennesker har indbyggede psykologiske mekanismer   er tilbøjelige til at 


Billede vi skal huske: En oplevende person, der glider igennem livet/verden og konstant mødes af indtryk, hvoraf nogle er potentielt informative... Opdaterer løbende holdninger pga. input afhængigt af ... bias eller ej?  

---

# Pege tilbage

- Zaller's RAS-model

- I stedet for faste holdninger giver det bedre mening at tænke på holdningsdannelse som process, der starter med information, som (måske) modtages og forstås (afhænger af politisk bevidsthed), måske accepteres og huskes (afhænger af prædispositioner), så det er mere eller mindre tilgængeligt, når der hurtigt skal rapporteres en holdning.

---

# Ugens tekster

Hvad, hvorfor?

Ikke så mange sider denne uge, men markant mere teknisk. Fortvivl ikke - vi kigger på det og hovedpointerne er ikke tekniske.

- Taber & Lodge (2016) - klassiker

- Druckman & McGrath (2019) - oversigt, begreber, status og udfordring, klima

- Damsbo-Svendsen (2021) - erfaret temperatur som heuristik

---

# State objective and roadmap

To do:

- Fokus på motivated reasoning - både Taber & Lodge og Druckman & McGrath


- Motivated reasoning har klare ligheder med Zaller - information... ikke opstået i tomrum. Men også klare forskelle i formål og tryk (vender tilbage til senere). 

---

# Druckman

- Reservoir af virkelig gode begrebsafklaringer: 

Indsæt bokse fra teksten. 

- Bayesiansk opdatering: Kort. 

- (Også) interesseret i den polariserede klimadebat i USA

- Dobbelt pointe om motivated reasoning: 

1. Motivated reasoning er en stærk ("maturing") teori, men
2. Man kan typisk ikke vide, hvilke mål folk faktisk er motiverede af (accuracy eller direction/partisan eller andet)! Vi kan ikke se forskel på, om udviklingen i holdninger skyldes directional motivated reasoning eller (mere ideel) accuracy-motivering med uenighed om, hvad der er troværdige og utroværdige kilder.    

- "source credibility" nævnes også af Zaller (s. 46), som ikke altid vigtigt ... 

---

# Taber & Lodge (2006)

Design! Elegant. Giv eksempler... 

## Hvordan operationaliseres mekanismerne?

1. Disconf.
2. Prior att.
3. Conf.

Evt. H4-H6.

---

# Forskelle fra Zaller

1. Mere psykologi, mikroniveau, individ, informationsprocessering

2. Også "detaljer": Fx kun i MR er der mulighed for "backlash", ikke hos Zaller, hvor det er accept eller ikke-accept. 

Lighed: S. 37: "People who are more ... selective ... "

---

# Diverse

Plots fra Bayes & Druckman ... Versus plot fra Zaller (s. 12) med race. 




---
class: title-slide, center, middle

# Heuristikker

---

# Hvad er en (kognitiv) heuristik?

Eksempler fra Lau & Redlawsk ..

Affekt-heuristik (Taber & Lodge, nævnes også af Zaller): Like eller dislike. 

---

# Damsbo-Svendsen (2021)

- RQ

- Er det information? Er det en (smart) heuristik? Er det dumt/uforklarligt?

---

# Big picture / sum up / andre teorier

- okay...

- Hvilke teorier har vi om holdninger? Meget informations-orienteret - og holdningsændring frem for "dannelse"

- Vigtigt (til sidst): Hvad har vi udeladt? Alt hvad I intuitivt tror påvirker holdninger - gør det ikke nødvendigvis, men *kan* gøre det -- kan være gode hypoteser. 

---

# Pege fremad

- Mere politisk adfærd

---




